services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: dockerfile
    image: catalogue #krishnamsettyrohith/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  mongodb:
    build:
      context: ./mongodb
      dockerfile: dockerfile
    image: mongodb:v1 #krishnamsettyrohith/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data
  user:
    build:
      context: ./user
      dockerfile: dockerfile
    image: user:v1 #krishnamsettyrohith/user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb
  cart:
    build:
      context: ./cart
      dockerfile: dockerfile
    image: cart:v1 #krishnamsettyrohith/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  mysql:
    build:
      context: ./mysql
      dockerfile: dockerfile
    image: mysql:v1 #krishnamsettyrohith/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  shipping:
    build:
      context: ./shipping
      dockerfile: dockerfile
    image: shipping:v1 #krishnamsettyrohith/shipping:v1
    container_name: shipping
    depends_on:
      - cart
      - mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=Roboshop@1
  payment:
    build:
      context: ./payment
      dockerfile: dockerfile
    image: payment:v1 #krishnamsettyrohith/payment:v1
    container_name: payment
    depends_on:
      - cart
      - user
      - rabbitmq
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: frontend:v1 #krishnamsettyrohith/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
      - cart
      - catalogue
      - user
      - shipping
      - payment
networks:
  default:
    driver: bridge
    name: roboshop
    external: true # true if you have created network manually using docker network command
# volumes:
#   mongodb:
#   redis:
#   mysql:
#   rabbitmq: